# Generated by Django 5.1.1 on 2024-10-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
